[package]
name = "dcalc"
version = "0.1.0"
edition = "2018"
authors = ["Ivan Rosales<ivan.rosales.rieloff@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"